Name:           ros-hydro-orientus-driver
Version:        0.0.4
Release:        0%{?dist}
Summary:        ROS orientus_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/orientus_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-diagnostic-updater
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-orientus-sdk-c
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-diagnostic-updater
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-orientus-sdk-c
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-sensor-msgs

%description
Driver for Orientus IMU

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Fri Nov 14 2014 Mitchell Wills <mwills@wpi.edu> - 0.0.4-0
- Autogenerated by Bloom

* Sun Nov 02 2014 Mitchell Wills <mwills@wpi.edu> - 0.0.2-0
- Autogenerated by Bloom

* Sat Nov 01 2014 Mitchell Wills <mwills@wpi.edu> - 0.0.1-0
- Autogenerated by Bloom

